# Enable C support
language: c

# Build matrix
matrix:
    include:
        - os: linux
          compiler: gcc 
        - os: linux
          compiler: clang
        - os: osx
          compiler: gcc
        - os: osx
          compiler: clang

# Build steps
script:
    - mkdir build
    - cd build
    - cmake .. && make VERBOSE=1
